//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Data.Mapping.EntityViewGenerationAttribute(typeof(Edm_EntityMappingGeneratedViews.ViewsForBaseEntitySetsC8658D1E67134FB02FE4C82AF8D085549393F07254BD9C7BD8C7858B495C2831))]

namespace Edm_EntityMappingGeneratedViews
{
    
    
    /// <Summary>
    /// The type contains views for EntitySets and AssociationSets that were generated at design time.
    /// </Summary>
    public sealed class ViewsForBaseEntitySetsC8658D1E67134FB02FE4C82AF8D085549393F07254BD9C7BD8C7858B495C2831 : System.Data.Mapping.EntityViewContainer
    {
        
        /// <Summary>
        /// The constructor stores the views for the extents and also the hash values generated based on the metadata and mapping closure and views.
        /// </Summary>
        public ViewsForBaseEntitySetsC8658D1E67134FB02FE4C82AF8D085549393F07254BD9C7BD8C7858B495C2831()
        {
            this.EdmEntityContainerName = "SBIIMS_JXC_TJBB_CGYCGEntities";
            this.StoreEntityContainerName = "WXDataDataModelStoreContainer";
            this.HashOverMappingClosure = "810c75418c4504926de8209145fe1cb5c052fa8474a2db2e0ed630270ddf5dc6";
            this.HashOverAllExtentViews = "fa3eefcebfb30e654d03518f8ddea3bf830d1f235f0f16a11c02c92eb4197a33";
            this.ViewCount = 24;
        }
        
        /// <Summary>
        /// The method returns the view for the index given.
        /// </Summary>
        protected override System.Collections.Generic.KeyValuePair<string, string> GetViewAt(int index)
        {
            if ((index == 0))
            {
                return GetView0();
            }
            if ((index == 1))
            {
                return GetView1();
            }
            if ((index == 2))
            {
                return GetView2();
            }
            if ((index == 3))
            {
                return GetView3();
            }
            if ((index == 4))
            {
                return GetView4();
            }
            if ((index == 5))
            {
                return GetView5();
            }
            if ((index == 6))
            {
                return GetView6();
            }
            if ((index == 7))
            {
                return GetView7();
            }
            if ((index == 8))
            {
                return GetView8();
            }
            if ((index == 9))
            {
                return GetView9();
            }
            if ((index == 10))
            {
                return GetView10();
            }
            if ((index == 11))
            {
                return GetView11();
            }
            if ((index == 12))
            {
                return GetView12();
            }
            if ((index == 13))
            {
                return GetView13();
            }
            if ((index == 14))
            {
                return GetView14();
            }
            if ((index == 15))
            {
                return GetView15();
            }
            if ((index == 16))
            {
                return GetView16();
            }
            if ((index == 17))
            {
                return GetView17();
            }
            if ((index == 18))
            {
                return GetView18();
            }
            if ((index == 19))
            {
                return GetView19();
            }
            if ((index == 20))
            {
                return GetView20();
            }
            if ((index == 21))
            {
                return GetView21();
            }
            if ((index == 22))
            {
                return GetView22();
            }
            if ((index == 23))
            {
                return GetView23();
            }
            throw new System.IndexOutOfRangeException();
        }
        
        /// <Summary>
        /// return view for WXDataDataModelStoreContainer.T_CK
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView0()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("WXDataDataModelStoreContainer.T_CK", @"
    SELECT VALUE -- Constructing T_CK
        [WX.Data.DataModel.Store.T_CK](T1.[T_CK.C_FBID], T1.[T_CK.C_GXRQ], T1.[T_CK.C_CJRQ], T1.[T_CK.C_ID], T1.[T_CK.C_MC], T1.[T_CK.C_XBH], T1.[T_CK.C_MCJM], T1.[T_CK.C_FZR], T1.[T_CK.C_DQ], T1.[T_CK.C_DQLJ], T1.[T_CK.C_LXDH], T1.[T_CK.C_LXDZ], T1.[T_CK.C_MRBZ], T1.[T_CK.C_JYBZ], T1.[T_CK.C_XTCSBZ], T1.[T_CK.C_XNBZ], T1.[T_CK.C_CZY], T1.[T_CK.C_JBR], T1.[T_CK.C_BZ])
    FROM (
        SELECT 
            T.C_FBID AS [T_CK.C_FBID], 
            T.C_GXRQ AS [T_CK.C_GXRQ], 
            T.C_CJRQ AS [T_CK.C_CJRQ], 
            T.C_ID AS [T_CK.C_ID], 
            T.C_MC AS [T_CK.C_MC], 
            T.C_XBH AS [T_CK.C_XBH], 
            T.C_MCJM AS [T_CK.C_MCJM], 
            T.C_FZR AS [T_CK.C_FZR], 
            T.C_DQ AS [T_CK.C_DQ], 
            T.C_DQLJ AS [T_CK.C_DQLJ], 
            T.C_LXDH AS [T_CK.C_LXDH], 
            T.C_LXDZ AS [T_CK.C_LXDZ], 
            T.C_MRBZ AS [T_CK.C_MRBZ], 
            T.C_JYBZ AS [T_CK.C_JYBZ], 
            T.C_XTCSBZ AS [T_CK.C_XTCSBZ], 
            T.C_XNBZ AS [T_CK.C_XNBZ], 
            T.C_CZY AS [T_CK.C_CZY], 
            T.C_JBR AS [T_CK.C_JBR], 
            T.C_BZ AS [T_CK.C_BZ], 
            True AS _from0
        FROM SBIIMS_JXC_TJBB_CGYCGEntities.T_CK AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for WXDataDataModelStoreContainer.T_DJ_JHGL
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView1()
        {
            System.Text.StringBuilder viewString = new System.Text.StringBuilder(4226);
            viewString.Append("\r\n    SELECT VALUE -- Constructing T_DJ_JHGL\r\n        [WX.Data.DataModel.Store.T");
            viewString.Append("_DJ_JHGL](T1.[T_DJ_JHGL.C_ZWYJSBZ], T1.[T_DJ_JHGL.C_ZWNJSBZ], T1.[T_DJ_JHGL.C_KD");
            viewString.Append("JQBZ], T1.[T_DJ_JHGL.C_JQBZ], T1.[T_DJ_JHGL.C_CKBZ], T1.[T_DJ_JHGL.C_RKBZ], T1.[");
            viewString.Append("T_DJ_JHGL.C_YSBZ], T1.[T_DJ_JHGL.C_HLPCBZ], T1.[T_DJ_JHGL.C_JQRQ], T1.[T_DJ_JHGL");
            viewString.Append(".C_ZWY], T1.[T_DJ_JHGL.C_ZWN], T1.[T_DJ_JHGL.C_FBID], T1.[T_DJ_JHGL.C_GXRQ], T1.");
            viewString.Append("[T_DJ_JHGL.C_CJRQ], T1.[T_DJ_JHGL.C_SJYRQ], T1.[T_DJ_JHGL.C_ID], T1.[T_DJ_JHGL.C");
            viewString.Append("_DJH], T1.[T_DJ_JHGL.C_DJLX], T1.[T_DJ_JHGL.C_WFDW], T1.[T_DJ_JHGL.C_GHS], T1.[T");
            viewString.Append("_DJ_JHGL.C_GHSJBR], T1.[T_DJ_JHGL.C_CCK], T1.[T_DJ_JHGL.C_RCK], T1.[T_DJ_JHGL.C_");
            viewString.Append("YZQJE], T1.[T_DJ_JHGL.C_DJYZQJE], T1.[T_DJ_JHGL.C_DJSZQJE], T1.[T_DJ_JHGL.C_DJYH");
            viewString.Append("JE], T1.[T_DJ_JHGL.C_VDJYZQJE], T1.[T_DJ_JHGL.C_VDJSZQJE], T1.[T_DJ_JHGL.C_VDJYH");
            viewString.Append("JE], T1.[T_DJ_JHGL.C_SZQJE], T1.[T_DJ_JHGL.C_JBR], T1.[T_DJ_JHGL.C_CZY], T1.[T_D");
            viewString.Append("J_JHGL.C_DYBZ], T1.[T_DJ_JHGL.C_THBZ], T1.[T_DJ_JHGL.C_DJZT], T1.[T_DJ_JHGL.C_CK");
            viewString.Append("SL], T1.[T_DJ_JHGL.C_RKSL], T1.[T_DJ_JHGL.C_CKJE], T1.[T_DJ_JHGL.C_RKJE], T1.[T_");
            viewString.Append("DJ_JHGL.C_CKCBJE], T1.[T_DJ_JHGL.C_RKCBJE], T1.[T_DJ_JHGL.C_DJLRJE], T1.[T_DJ_JH");
            viewString.Append("GL.C_DJJYLRL], T1.[T_DJ_JHGL.C_DJCBLRL], T1.[T_DJ_JHGL.C_SPYHJE], T1.[T_DJ_JHGL.");
            viewString.Append("C_DJTMSL], T1.[T_DJ_JHGL.C_WFYHZH], T1.[T_DJ_JHGL.C_GHSYHZH], T1.[T_DJ_JHGL.C_WF");
            viewString.Append("ZHLB], T1.[T_DJ_JHGL.C_GHSZHLB], T1.[T_DJ_JHGL.C_ZFFS], T1.[T_DJ_JHGL.C_GLDJ], T");
            viewString.Append("1.[T_DJ_JHGL.C_SHR], T1.[T_DJ_JHGL.C_GLDJH], T1.[T_DJ_JHGL.C_BZ])\r\n    FROM (\r\n ");
            viewString.Append("       SELECT \r\n            T.C_ZWYJSBZ AS [T_DJ_JHGL.C_ZWYJSBZ], \r\n            ");
            viewString.Append("T.C_ZWNJSBZ AS [T_DJ_JHGL.C_ZWNJSBZ], \r\n            T.C_KDJQBZ AS [T_DJ_JHGL.C_K");
            viewString.Append("DJQBZ], \r\n            T.C_JQBZ AS [T_DJ_JHGL.C_JQBZ], \r\n            T.C_CKBZ AS ");
            viewString.Append("[T_DJ_JHGL.C_CKBZ], \r\n            T.C_RKBZ AS [T_DJ_JHGL.C_RKBZ], \r\n            ");
            viewString.Append("T.C_YSBZ AS [T_DJ_JHGL.C_YSBZ], \r\n            T.C_HLPCBZ AS [T_DJ_JHGL.C_HLPCBZ]");
            viewString.Append(", \r\n            T.C_JQRQ AS [T_DJ_JHGL.C_JQRQ], \r\n            T.C_ZWY AS [T_DJ_J");
            viewString.Append("HGL.C_ZWY], \r\n            T.C_ZWN AS [T_DJ_JHGL.C_ZWN], \r\n            T.C_FBID A");
            viewString.Append("S [T_DJ_JHGL.C_FBID], \r\n            T.C_GXRQ AS [T_DJ_JHGL.C_GXRQ], \r\n          ");
            viewString.Append("  T.C_CJRQ AS [T_DJ_JHGL.C_CJRQ], \r\n            T.C_SJYRQ AS [T_DJ_JHGL.C_SJYRQ]");
            viewString.Append(", \r\n            T.C_ID AS [T_DJ_JHGL.C_ID], \r\n            T.C_DJH AS [T_DJ_JHGL.");
            viewString.Append("C_DJH], \r\n            T.C_DJLX AS [T_DJ_JHGL.C_DJLX], \r\n            T.C_WFDW AS ");
            viewString.Append("[T_DJ_JHGL.C_WFDW], \r\n            T.C_GHS AS [T_DJ_JHGL.C_GHS], \r\n            T.");
            viewString.Append("C_GHSJBR AS [T_DJ_JHGL.C_GHSJBR], \r\n            T.C_CCK AS [T_DJ_JHGL.C_CCK], \r\n");
            viewString.Append("            T.C_RCK AS [T_DJ_JHGL.C_RCK], \r\n            T.C_YZQJE AS [T_DJ_JHGL.");
            viewString.Append("C_YZQJE], \r\n            T.C_DJYZQJE AS [T_DJ_JHGL.C_DJYZQJE], \r\n            T.C_");
            viewString.Append("DJSZQJE AS [T_DJ_JHGL.C_DJSZQJE], \r\n            T.C_DJYHJE AS [T_DJ_JHGL.C_DJYHJ");
            viewString.Append("E], \r\n            T.C_VDJYZQJE AS [T_DJ_JHGL.C_VDJYZQJE], \r\n            T.C_VDJS");
            viewString.Append("ZQJE AS [T_DJ_JHGL.C_VDJSZQJE], \r\n            T.C_VDJYHJE AS [T_DJ_JHGL.C_VDJYHJ");
            viewString.Append("E], \r\n            T.C_SZQJE AS [T_DJ_JHGL.C_SZQJE], \r\n            T.C_JBR AS [T_");
            viewString.Append("DJ_JHGL.C_JBR], \r\n            T.C_CZY AS [T_DJ_JHGL.C_CZY], \r\n            T.C_DY");
            viewString.Append("BZ AS [T_DJ_JHGL.C_DYBZ], \r\n            T.C_THBZ AS [T_DJ_JHGL.C_THBZ], \r\n      ");
            viewString.Append("      T.C_DJZT AS [T_DJ_JHGL.C_DJZT], \r\n            T.C_CKSL AS [T_DJ_JHGL.C_CKS");
            viewString.Append("L], \r\n            T.C_RKSL AS [T_DJ_JHGL.C_RKSL], \r\n            T.C_CKJE AS [T_D");
            viewString.Append("J_JHGL.C_CKJE], \r\n            T.C_RKJE AS [T_DJ_JHGL.C_RKJE], \r\n            T.C_");
            viewString.Append("CKCBJE AS [T_DJ_JHGL.C_CKCBJE], \r\n            T.C_RKCBJE AS [T_DJ_JHGL.C_RKCBJE]");
            viewString.Append(", \r\n            T.C_DJLRJE AS [T_DJ_JHGL.C_DJLRJE], \r\n            T.C_DJJYLRL AS");
            viewString.Append(" [T_DJ_JHGL.C_DJJYLRL], \r\n            T.C_DJCBLRL AS [T_DJ_JHGL.C_DJCBLRL], \r\n  ");
            viewString.Append("          T.C_SPYHJE AS [T_DJ_JHGL.C_SPYHJE], \r\n            T.C_DJTMSL AS [T_DJ_");
            viewString.Append("JHGL.C_DJTMSL], \r\n            T.C_WFYHZH AS [T_DJ_JHGL.C_WFYHZH], \r\n            ");
            viewString.Append("T.C_GHSYHZH AS [T_DJ_JHGL.C_GHSYHZH], \r\n            T.C_WFZHLB AS [T_DJ_JHGL.C_W");
            viewString.Append("FZHLB], \r\n            T.C_GHSZHLB AS [T_DJ_JHGL.C_GHSZHLB], \r\n            T.C_ZF");
            viewString.Append("FS AS [T_DJ_JHGL.C_ZFFS], \r\n            T.C_GLDJ AS [T_DJ_JHGL.C_GLDJ], \r\n      ");
            viewString.Append("      T.C_SHR AS [T_DJ_JHGL.C_SHR], \r\n            T.C_GLDJH AS [T_DJ_JHGL.C_GLDJ");
            viewString.Append("H], \r\n            T.C_BZ AS [T_DJ_JHGL.C_BZ], \r\n            True AS _from0\r\n    ");
            viewString.Append("    FROM SBIIMS_JXC_TJBB_CGYCGEntities.T_DJ_JHGL AS T\r\n    ) AS T1");
            return new System.Collections.Generic.KeyValuePair<string, string>("WXDataDataModelStoreContainer.T_DJ_JHGL", viewString.ToString());
        }
        
        /// <Summary>
        /// return view for WXDataDataModelStoreContainer.T_DJLX
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView2()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("WXDataDataModelStoreContainer.T_DJLX", @"
    SELECT VALUE -- Constructing T_DJLX
        [WX.Data.DataModel.Store.T_DJLX](T1.[T_DJLX.C_DM], T1.[T_DJLX.C_LX], T1.[T_DJLX.C_QZ], T1.[T_DJLX.C_LB], T1.[T_DJLX.C_JYBZ], T1.[T_DJLX.C_BZ])
    FROM (
        SELECT 
            T.C_DM AS [T_DJLX.C_DM], 
            T.C_LX AS [T_DJLX.C_LX], 
            T.C_QZ AS [T_DJLX.C_QZ], 
            T.C_LB AS [T_DJLX.C_LB], 
            T.C_JYBZ AS [T_DJLX.C_JYBZ], 
            T.C_BZ AS [T_DJLX.C_BZ], 
            True AS _from0
        FROM SBIIMS_JXC_TJBB_CGYCGEntities.T_DJLX AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for WXDataDataModelStoreContainer.T_DJSP_JHGL
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView3()
        {
            System.Text.StringBuilder viewString = new System.Text.StringBuilder(3348);
            viewString.Append("\r\n    SELECT VALUE -- Constructing T_DJSP_JHGL\r\n        [WX.Data.DataModel.Store");
            viewString.Append(".T_DJSP_JHGL](T1.[T_DJSP_JHGL.C_ZWYJSBZ], T1.[T_DJSP_JHGL.C_ZWNJSBZ], T1.[T_DJSP");
            viewString.Append("_JHGL.C_CKBZ], T1.[T_DJSP_JHGL.C_RKBZ], T1.[T_DJSP_JHGL.C_HLPCBZ], T1.[T_DJSP_JH");
            viewString.Append("GL.C_ZWY], T1.[T_DJSP_JHGL.C_ZWN], T1.[T_DJSP_JHGL.C_FBID], T1.[T_DJSP_JHGL.C_CJ");
            viewString.Append("RQ], T1.[T_DJSP_JHGL.C_ID], T1.[T_DJSP_JHGL.C_DJID], T1.[T_DJSP_JHGL.C_SP], T1.[");
            viewString.Append("T_DJSP_JHGL.C_PC], T1.[T_DJSP_JHGL.C_XH], T1.[T_DJSP_JHGL.C_SCRQ], T1.[T_DJSP_JH");
            viewString.Append("GL.C_YXRQ], T1.[T_DJSP_JHGL.C_SPPH], T1.[T_DJSP_JHGL.C_JJ], T1.[T_DJSP_JHGL.C_DJ");
            viewString.Append("], T1.[T_DJSP_JHGL.C_ZKL], T1.[T_DJSP_JHGL.C_ZHJ], T1.[T_DJSP_JHGL.C_SL], T1.[T_");
            viewString.Append("DJSP_JHGL.C_ZJE], T1.[T_DJSP_JHGL.C_ZHJE], T1.[T_DJSP_JHGL.C_VSL], T1.[T_DJSP_JH");
            viewString.Append("GL.C_VZJE], T1.[T_DJSP_JHGL.C_VZHJE], T1.[T_DJSP_JHGL.C_CBJE], T1.[T_DJSP_JHGL.C");
            viewString.Append("_VCBJE], T1.[T_DJSP_JHGL.C_CGGHS], T1.[T_DJSP_JHGL.C_SPLRJE], T1.[T_DJSP_JHGL.C_");
            viewString.Append("SPJYLRL], T1.[T_DJSP_JHGL.C_SPCBLRL], T1.[T_DJSP_JHGL.C_SPYHJE], T1.[T_DJSP_JHGL");
            viewString.Append(".C_DJH], T1.[T_DJSP_JHGL.C_DJLX], T1.[T_DJSP_JHGL.C_CCK], T1.[T_DJSP_JHGL.C_RCK]");
            viewString.Append(", T1.[T_DJSP_JHGL.C_JBR], T1.[T_DJSP_JHGL.C_CZY], T1.[T_DJSP_JHGL.C_CGDJID], T1.");
            viewString.Append("[T_DJSP_JHGL.C_SHR], T1.[T_DJSP_JHGL.C_BZ])\r\n    FROM (\r\n        SELECT \r\n      ");
            viewString.Append("      T.C_ZWYJSBZ AS [T_DJSP_JHGL.C_ZWYJSBZ], \r\n            T.C_ZWNJSBZ AS [T_DJ");
            viewString.Append("SP_JHGL.C_ZWNJSBZ], \r\n            T.C_CKBZ AS [T_DJSP_JHGL.C_CKBZ], \r\n          ");
            viewString.Append("  T.C_RKBZ AS [T_DJSP_JHGL.C_RKBZ], \r\n            T.C_HLPCBZ AS [T_DJSP_JHGL.C_H");
            viewString.Append("LPCBZ], \r\n            T.C_ZWY AS [T_DJSP_JHGL.C_ZWY], \r\n            T.C_ZWN AS [");
            viewString.Append("T_DJSP_JHGL.C_ZWN], \r\n            T.C_FBID AS [T_DJSP_JHGL.C_FBID], \r\n          ");
            viewString.Append("  T.C_CJRQ AS [T_DJSP_JHGL.C_CJRQ], \r\n            T.C_ID AS [T_DJSP_JHGL.C_ID], ");
            viewString.Append("\r\n            T.C_DJID AS [T_DJSP_JHGL.C_DJID], \r\n            T.C_SP AS [T_DJSP_");
            viewString.Append("JHGL.C_SP], \r\n            T.C_PC AS [T_DJSP_JHGL.C_PC], \r\n            T.C_XH AS ");
            viewString.Append("[T_DJSP_JHGL.C_XH], \r\n            T.C_SCRQ AS [T_DJSP_JHGL.C_SCRQ], \r\n          ");
            viewString.Append("  T.C_YXRQ AS [T_DJSP_JHGL.C_YXRQ], \r\n            T.C_SPPH AS [T_DJSP_JHGL.C_SPP");
            viewString.Append("H], \r\n            T.C_JJ AS [T_DJSP_JHGL.C_JJ], \r\n            T.C_DJ AS [T_DJSP_");
            viewString.Append("JHGL.C_DJ], \r\n            T.C_ZKL AS [T_DJSP_JHGL.C_ZKL], \r\n            T.C_ZHJ ");
            viewString.Append("AS [T_DJSP_JHGL.C_ZHJ], \r\n            T.C_SL AS [T_DJSP_JHGL.C_SL], \r\n          ");
            viewString.Append("  T.C_ZJE AS [T_DJSP_JHGL.C_ZJE], \r\n            T.C_ZHJE AS [T_DJSP_JHGL.C_ZHJE]");
            viewString.Append(", \r\n            T.C_VSL AS [T_DJSP_JHGL.C_VSL], \r\n            T.C_VZJE AS [T_DJS");
            viewString.Append("P_JHGL.C_VZJE], \r\n            T.C_VZHJE AS [T_DJSP_JHGL.C_VZHJE], \r\n            ");
            viewString.Append("T.C_CBJE AS [T_DJSP_JHGL.C_CBJE], \r\n            T.C_VCBJE AS [T_DJSP_JHGL.C_VCBJ");
            viewString.Append("E], \r\n            T.C_CGGHS AS [T_DJSP_JHGL.C_CGGHS], \r\n            T.C_SPLRJE A");
            viewString.Append("S [T_DJSP_JHGL.C_SPLRJE], \r\n            T.C_SPJYLRL AS [T_DJSP_JHGL.C_SPJYLRL], ");
            viewString.Append("\r\n            T.C_SPCBLRL AS [T_DJSP_JHGL.C_SPCBLRL], \r\n            T.C_SPYHJE A");
            viewString.Append("S [T_DJSP_JHGL.C_SPYHJE], \r\n            T.C_DJH AS [T_DJSP_JHGL.C_DJH], \r\n      ");
            viewString.Append("      T.C_DJLX AS [T_DJSP_JHGL.C_DJLX], \r\n            T.C_CCK AS [T_DJSP_JHGL.C_");
            viewString.Append("CCK], \r\n            T.C_RCK AS [T_DJSP_JHGL.C_RCK], \r\n            T.C_JBR AS [T_");
            viewString.Append("DJSP_JHGL.C_JBR], \r\n            T.C_CZY AS [T_DJSP_JHGL.C_CZY], \r\n            T.");
            viewString.Append("C_CGDJID AS [T_DJSP_JHGL.C_CGDJID], \r\n            T.C_SHR AS [T_DJSP_JHGL.C_SHR]");
            viewString.Append(", \r\n            T.C_BZ AS [T_DJSP_JHGL.C_BZ], \r\n            True AS _from0\r\n    ");
            viewString.Append("    FROM SBIIMS_JXC_TJBB_CGYCGEntities.T_DJSP_JHGL AS T\r\n    ) AS T1");
            return new System.Collections.Generic.KeyValuePair<string, string>("WXDataDataModelStoreContainer.T_DJSP_JHGL", viewString.ToString());
        }
        
        /// <Summary>
        /// return view for WXDataDataModelStoreContainer.T_GHS
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView4()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("WXDataDataModelStoreContainer.T_GHS", "\r\n    SELECT VALUE -- Constructing T_GHS\r\n        [WX.Data.DataModel.Store.T_GHS]" +
                    "(T1.[T_GHS.C_FBID], T1.[T_GHS.C_GXRQ], T1.[T_GHS.C_CJRQ], T1.[T_GHS.C_ID], T1.[T" +
                    "_GHS.C_MC], T1.[T_GHS.C_MCJM], T1.[T_GHS.C_XBH], T1.[T_GHS.C_LB], T1.[T_GHS.C_LX" +
                    "], T1.[T_GHS.C_DJ], T1.[T_GHS.C_LXDH], T1.[T_GHS.C_LXDZ], T1.[T_GHS.C_XYJF], T1." +
                    "[T_GHS.C_GHJF], T1.[T_GHS.C_DQ], T1.[T_GHS.C_MRBZ], T1.[T_GHS.C_JYBZ], T1.[T_GHS" +
                    ".C_XTCSBZ], T1.[T_GHS.C_XNBZ], T1.[T_GHS.C_CZY], T1.[T_GHS.C_JBR], T1.[T_GHS.C_L" +
                    "XR], T1.[T_GHS.C_DY], T1.[T_GHS.C_BZ])\r\n    FROM (\r\n        SELECT \r\n           " +
                    " T.C_FBID AS [T_GHS.C_FBID], \r\n            T.C_GXRQ AS [T_GHS.C_GXRQ], \r\n       " +
                    "     T.C_CJRQ AS [T_GHS.C_CJRQ], \r\n            T.C_ID AS [T_GHS.C_ID], \r\n       " +
                    "     T.C_MC AS [T_GHS.C_MC], \r\n            T.C_MCJM AS [T_GHS.C_MCJM], \r\n       " +
                    "     T.C_XBH AS [T_GHS.C_XBH], \r\n            T.C_LB AS [T_GHS.C_LB], \r\n         " +
                    "   T.C_LX AS [T_GHS.C_LX], \r\n            T.C_DJ AS [T_GHS.C_DJ], \r\n            T" +
                    ".C_LXDH AS [T_GHS.C_LXDH], \r\n            T.C_LXDZ AS [T_GHS.C_LXDZ], \r\n         " +
                    "   T.C_XYJF AS [T_GHS.C_XYJF], \r\n            T.C_GHJF AS [T_GHS.C_GHJF], \r\n     " +
                    "       T.C_DQ AS [T_GHS.C_DQ], \r\n            T.C_MRBZ AS [T_GHS.C_MRBZ], \r\n     " +
                    "       T.C_JYBZ AS [T_GHS.C_JYBZ], \r\n            T.C_XTCSBZ AS [T_GHS.C_XTCSBZ]," +
                    " \r\n            T.C_XNBZ AS [T_GHS.C_XNBZ], \r\n            T.C_CZY AS [T_GHS.C_CZY" +
                    "], \r\n            T.C_JBR AS [T_GHS.C_JBR], \r\n            T.C_LXR AS [T_GHS.C_LXR" +
                    "], \r\n            T.C_DY AS [T_GHS.C_DY], \r\n            T.C_BZ AS [T_GHS.C_BZ], \r" +
                    "\n            True AS _from0\r\n        FROM SBIIMS_JXC_TJBB_CGYCGEntities.T_GHS AS" +
                    " T\r\n    ) AS T1");
        }
        
        /// <Summary>
        /// return view for WXDataDataModelStoreContainer.T_KCSP_DQZT
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView5()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("WXDataDataModelStoreContainer.T_KCSP_DQZT", @"
    SELECT VALUE -- Constructing T_KCSP_DQZT
        [WX.Data.DataModel.Store.T_KCSP_DQZT](T1.[T_KCSP_DQZT.C_FBID], T1.[T_KCSP_DQZT.C_GXRQ], T1.[T_KCSP_DQZT.C_CJRQ], T1.[T_KCSP_DQZT.C_KCSP], T1.[T_KCSP_DQZT.C_KCSL], T1.[T_KCSP_DQZT.C_KCSX], T1.[T_KCSP_DQZT.C_KCXX], T1.[T_KCSP_DQZT.C_CBJJ], T1.[T_KCSP_DQZT.C_SCJJ], T1.[T_KCSP_DQZT.C_CBJE], T1.[T_KCSP_DQZT.C_RKSL], T1.[T_KCSP_DQZT.C_CKSL])
    FROM (
        SELECT 
            T.C_FBID AS [T_KCSP_DQZT.C_FBID], 
            T.C_GXRQ AS [T_KCSP_DQZT.C_GXRQ], 
            T.C_CJRQ AS [T_KCSP_DQZT.C_CJRQ], 
            T.C_KCSP AS [T_KCSP_DQZT.C_KCSP], 
            T.C_KCSL AS [T_KCSP_DQZT.C_KCSL], 
            T.C_KCSX AS [T_KCSP_DQZT.C_KCSX], 
            T.C_KCXX AS [T_KCSP_DQZT.C_KCXX], 
            T.C_CBJJ AS [T_KCSP_DQZT.C_CBJJ], 
            T.C_SCJJ AS [T_KCSP_DQZT.C_SCJJ], 
            T.C_CBJE AS [T_KCSP_DQZT.C_CBJE], 
            T.C_RKSL AS [T_KCSP_DQZT.C_RKSL], 
            T.C_CKSL AS [T_KCSP_DQZT.C_CKSL], 
            True AS _from0
        FROM SBIIMS_JXC_TJBB_CGYCGEntities.T_KCSP_DQZT AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for WXDataDataModelStoreContainer.T_QFMX_JHGL
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView6()
        {
            System.Text.StringBuilder viewString = new System.Text.StringBuilder(3386);
            viewString.Append("\r\n    SELECT VALUE -- Constructing T_QFMX_JHGL\r\n        [WX.Data.DataModel.Store");
            viewString.Append(".T_QFMX_JHGL](T1.[T_QFMX_JHGL.C_CKBZ], T1.[T_QFMX_JHGL.C_RKBZ], T1.[T_QFMX_JHGL.");
            viewString.Append("C_QSBZ], T1.[T_QFMX_JHGL.C_ZWNJSBZ], T1.[T_QFMX_JHGL.C_ZWYJSBZ], T1.[T_QFMX_JHGL");
            viewString.Append(".C_ZWN], T1.[T_QFMX_JHGL.C_ZWY], T1.[T_QFMX_JHGL.C_FBID], T1.[T_QFMX_JHGL.C_GXRQ");
            viewString.Append("], T1.[T_QFMX_JHGL.C_CJRQ], T1.[T_QFMX_JHGL.C_QFJE], T1.[T_QFMX_JHGL.C_SZQJE], T");
            viewString.Append("1.[T_QFMX_JHGL.C_DJ], T1.[T_QFMX_JHGL.C_DJH], T1.[T_QFMX_JHGL.C_DJLX], T1.[T_QFM");
            viewString.Append("X_JHGL.C_GHS], T1.[T_QFMX_JHGL.C_GHSJBR], T1.[T_QFMX_JHGL.C_YZQJE], T1.[T_QFMX_J");
            viewString.Append("HGL.C_DJYZQJE], T1.[T_QFMX_JHGL.C_DJSZQJE], T1.[T_QFMX_JHGL.C_DJYHJE], T1.[T_QFM");
            viewString.Append("X_JHGL.C_VDJYZQJE], T1.[T_QFMX_JHGL.C_VDJSZQJE], T1.[T_QFMX_JHGL.C_VDJYHJE], T1.");
            viewString.Append("[T_QFMX_JHGL.C_CCK], T1.[T_QFMX_JHGL.C_RCK], T1.[T_QFMX_JHGL.C_CKSL], T1.[T_QFMX");
            viewString.Append("_JHGL.C_RKSL], T1.[T_QFMX_JHGL.C_CKJE], T1.[T_QFMX_JHGL.C_RKJE], T1.[T_QFMX_JHGL");
            viewString.Append(".C_CKCBJE], T1.[T_QFMX_JHGL.C_RKCBJE], T1.[T_QFMX_JHGL.C_JBR], T1.[T_QFMX_JHGL.C");
            viewString.Append("_CZY], T1.[T_QFMX_JHGL.C_DJLRJE], T1.[T_QFMX_JHGL.C_DJJYLRL], T1.[T_QFMX_JHGL.C_");
            viewString.Append("DJCBLRL], T1.[T_QFMX_JHGL.C_SPYHJE], T1.[T_QFMX_JHGL.C_DJTMSL], T1.[T_QFMX_JHGL.");
            viewString.Append("C_GLDJ], T1.[T_QFMX_JHGL.C_SHR], T1.[T_QFMX_JHGL.C_BZ])\r\n    FROM (\r\n        SEL");
            viewString.Append("ECT \r\n            T.C_CKBZ AS [T_QFMX_JHGL.C_CKBZ], \r\n            T.C_RKBZ AS [T");
            viewString.Append("_QFMX_JHGL.C_RKBZ], \r\n            T.C_QSBZ AS [T_QFMX_JHGL.C_QSBZ], \r\n          ");
            viewString.Append("  T.C_ZWNJSBZ AS [T_QFMX_JHGL.C_ZWNJSBZ], \r\n            T.C_ZWYJSBZ AS [T_QFMX_J");
            viewString.Append("HGL.C_ZWYJSBZ], \r\n            T.C_ZWN AS [T_QFMX_JHGL.C_ZWN], \r\n            T.C_");
            viewString.Append("ZWY AS [T_QFMX_JHGL.C_ZWY], \r\n            T.C_FBID AS [T_QFMX_JHGL.C_FBID], \r\n  ");
            viewString.Append("          T.C_GXRQ AS [T_QFMX_JHGL.C_GXRQ], \r\n            T.C_CJRQ AS [T_QFMX_JH");
            viewString.Append("GL.C_CJRQ], \r\n            T.C_QFJE AS [T_QFMX_JHGL.C_QFJE], \r\n            T.C_SZ");
            viewString.Append("QJE AS [T_QFMX_JHGL.C_SZQJE], \r\n            T.C_DJ AS [T_QFMX_JHGL.C_DJ], \r\n    ");
            viewString.Append("        T.C_DJH AS [T_QFMX_JHGL.C_DJH], \r\n            T.C_DJLX AS [T_QFMX_JHGL.C");
            viewString.Append("_DJLX], \r\n            T.C_GHS AS [T_QFMX_JHGL.C_GHS], \r\n            T.C_GHSJBR A");
            viewString.Append("S [T_QFMX_JHGL.C_GHSJBR], \r\n            T.C_YZQJE AS [T_QFMX_JHGL.C_YZQJE], \r\n  ");
            viewString.Append("          T.C_DJYZQJE AS [T_QFMX_JHGL.C_DJYZQJE], \r\n            T.C_DJSZQJE AS [");
            viewString.Append("T_QFMX_JHGL.C_DJSZQJE], \r\n            T.C_DJYHJE AS [T_QFMX_JHGL.C_DJYHJE], \r\n  ");
            viewString.Append("          T.C_VDJYZQJE AS [T_QFMX_JHGL.C_VDJYZQJE], \r\n            T.C_VDJSZQJE A");
            viewString.Append("S [T_QFMX_JHGL.C_VDJSZQJE], \r\n            T.C_VDJYHJE AS [T_QFMX_JHGL.C_VDJYHJE]");
            viewString.Append(", \r\n            T.C_CCK AS [T_QFMX_JHGL.C_CCK], \r\n            T.C_RCK AS [T_QFMX");
            viewString.Append("_JHGL.C_RCK], \r\n            T.C_CKSL AS [T_QFMX_JHGL.C_CKSL], \r\n            T.C_");
            viewString.Append("RKSL AS [T_QFMX_JHGL.C_RKSL], \r\n            T.C_CKJE AS [T_QFMX_JHGL.C_CKJE], \r\n");
            viewString.Append("            T.C_RKJE AS [T_QFMX_JHGL.C_RKJE], \r\n            T.C_CKCBJE AS [T_QFM");
            viewString.Append("X_JHGL.C_CKCBJE], \r\n            T.C_RKCBJE AS [T_QFMX_JHGL.C_RKCBJE], \r\n        ");
            viewString.Append("    T.C_JBR AS [T_QFMX_JHGL.C_JBR], \r\n            T.C_CZY AS [T_QFMX_JHGL.C_CZY]");
            viewString.Append(", \r\n            T.C_DJLRJE AS [T_QFMX_JHGL.C_DJLRJE], \r\n            T.C_DJJYLRL ");
            viewString.Append("AS [T_QFMX_JHGL.C_DJJYLRL], \r\n            T.C_DJCBLRL AS [T_QFMX_JHGL.C_DJCBLRL]");
            viewString.Append(", \r\n            T.C_SPYHJE AS [T_QFMX_JHGL.C_SPYHJE], \r\n            T.C_DJTMSL A");
            viewString.Append("S [T_QFMX_JHGL.C_DJTMSL], \r\n            T.C_GLDJ AS [T_QFMX_JHGL.C_GLDJ], \r\n    ");
            viewString.Append("        T.C_SHR AS [T_QFMX_JHGL.C_SHR], \r\n            T.C_BZ AS [T_QFMX_JHGL.C_B");
            viewString.Append("Z], \r\n            True AS _from0\r\n        FROM SBIIMS_JXC_TJBB_CGYCGEntities.T_Q");
            viewString.Append("FMX_JHGL AS T\r\n    ) AS T1");
            return new System.Collections.Generic.KeyValuePair<string, string>("WXDataDataModelStoreContainer.T_QFMX_JHGL", viewString.ToString());
        }
        
        /// <Summary>
        /// return view for WXDataDataModelStoreContainer.T_RZ
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView7()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("WXDataDataModelStoreContainer.T_RZ", @"
    SELECT VALUE -- Constructing T_RZ
        [WX.Data.DataModel.Store.T_RZ](T1.[T_RZ.C_FBID], T1.[T_RZ.C_CJRQ], T1.[T_RZ.C_ID], T1.[T_RZ.C_JLID], T1.[T_RZ.C_YWLX], T1.[T_RZ.C_YWLXMC], T1.[T_RZ.C_CZLX], T1.[T_RZ.C_CZLXMC], T1.[T_RZ.C_CZY], T1.[T_RZ.C_CZYXM], T1.[T_RZ.C_BM], T1.[T_RZ.C_BBM], T1.[T_RZ.C_ZBM], T1.[T_RZ.C_ZBBM], T1.[T_RZ.C_ZBSL], T1.[T_RZ.C_HOST], T1.[T_RZ.C_IP], T1.[T_RZ.C_NR])
    FROM (
        SELECT 
            T.C_FBID AS [T_RZ.C_FBID], 
            T.C_CJRQ AS [T_RZ.C_CJRQ], 
            T.C_ID AS [T_RZ.C_ID], 
            T.C_JLID AS [T_RZ.C_JLID], 
            T.C_YWLX AS [T_RZ.C_YWLX], 
            T.C_YWLXMC AS [T_RZ.C_YWLXMC], 
            T.C_CZLX AS [T_RZ.C_CZLX], 
            T.C_CZLXMC AS [T_RZ.C_CZLXMC], 
            T.C_CZY AS [T_RZ.C_CZY], 
            T.C_CZYXM AS [T_RZ.C_CZYXM], 
            T.C_BM AS [T_RZ.C_BM], 
            T.C_BBM AS [T_RZ.C_BBM], 
            T.C_ZBM AS [T_RZ.C_ZBM], 
            T.C_ZBBM AS [T_RZ.C_ZBBM], 
            T.C_ZBSL AS [T_RZ.C_ZBSL], 
            T.C_HOST AS [T_RZ.C_HOST], 
            T.C_IP AS [T_RZ.C_IP], 
            T.C_NR AS [T_RZ.C_NR], 
            True AS _from0
        FROM SBIIMS_JXC_TJBB_CGYCGEntities.T_RZ AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for WXDataDataModelStoreContainer.T_SP
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView8()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("WXDataDataModelStoreContainer.T_SP", "\r\n    SELECT VALUE -- Constructing T_SP\r\n        [WX.Data.DataModel.Store.T_SP](T" +
                    "1.[T_SP.C_JYBZ], T1.[T_SP.C_XNBZ], T1.[T_SP.C_XTCSBZ], T1.[T_SP.C_FBID], T1.[T_S" +
                    "P.C_ID], T1.[T_SP.C_GXRQ], T1.[T_SP.C_CJRQ], T1.[T_SP.C_XBH], T1.[T_SP.C_MC], T1" +
                    ".[T_SP.C_MCJM], T1.[T_SP.C_DW], T1.[T_SP.C_GGXH], T1.[T_SP.C_YS], T1.[T_SP.C_SPL" +
                    "B], T1.[T_SP.C_SCCS], T1.[T_SP.C_KCSX], T1.[T_SP.C_KCXX], T1.[T_SP.C_YSJJ], T1.[" +
                    "T_SP.C_YSSJ], T1.[T_SP.C_BZQX], T1.[T_SP.C_BHQX], T1.[T_SP.C_CZY], T1.[T_SP.C_JB" +
                    "R], T1.[T_SP.C_TM], T1.[T_SP.C_BZ])\r\n    FROM (\r\n        SELECT \r\n            T." +
                    "C_JYBZ AS [T_SP.C_JYBZ], \r\n            T.C_XNBZ AS [T_SP.C_XNBZ], \r\n            " +
                    "T.C_XTCSBZ AS [T_SP.C_XTCSBZ], \r\n            T.C_FBID AS [T_SP.C_FBID], \r\n      " +
                    "      T.C_ID AS [T_SP.C_ID], \r\n            T.C_GXRQ AS [T_SP.C_GXRQ], \r\n        " +
                    "    T.C_CJRQ AS [T_SP.C_CJRQ], \r\n            T.C_XBH AS [T_SP.C_XBH], \r\n        " +
                    "    T.C_MC AS [T_SP.C_MC], \r\n            T.C_MCJM AS [T_SP.C_MCJM], \r\n          " +
                    "  T.C_DW AS [T_SP.C_DW], \r\n            T.C_GGXH AS [T_SP.C_GGXH], \r\n            " +
                    "T.C_YS AS [T_SP.C_YS], \r\n            T.C_SPLB AS [T_SP.C_SPLB], \r\n            T." +
                    "C_SCCS AS [T_SP.C_SCCS], \r\n            T.C_KCSX AS [T_SP.C_KCSX], \r\n            " +
                    "T.C_KCXX AS [T_SP.C_KCXX], \r\n            T.C_YSJJ AS [T_SP.C_YSJJ], \r\n          " +
                    "  T.C_YSSJ AS [T_SP.C_YSSJ], \r\n            T.C_BZQX AS [T_SP.C_BZQX], \r\n        " +
                    "    T.C_BHQX AS [T_SP.C_BHQX], \r\n            T.C_CZY AS [T_SP.C_CZY], \r\n        " +
                    "    T.C_JBR AS [T_SP.C_JBR], \r\n            T.C_TM AS [T_SP.C_TM], \r\n            " +
                    "T.C_BZ AS [T_SP.C_BZ], \r\n            True AS _from0\r\n        FROM SBIIMS_JXC_TJB" +
                    "B_CGYCGEntities.T_SP AS T\r\n    ) AS T1");
        }
        
        /// <Summary>
        /// return view for WXDataDataModelStoreContainer.T_SPDW
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView9()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("WXDataDataModelStoreContainer.T_SPDW", @"
    SELECT VALUE -- Constructing T_SPDW
        [WX.Data.DataModel.Store.T_SPDW](T1.[T_SPDW.C_DM], T1.[T_SPDW.C_DW], T1.[T_SPDW.C_JYBZ], T1.[T_SPDW.C_XTCSBZ], T1.[T_SPDW.C_BZ])
    FROM (
        SELECT 
            T.C_DM AS [T_SPDW.C_DM], 
            T.C_DW AS [T_SPDW.C_DW], 
            T.C_JYBZ AS [T_SPDW.C_JYBZ], 
            T.C_XTCSBZ AS [T_SPDW.C_XTCSBZ], 
            T.C_BZ AS [T_SPDW.C_BZ], 
            True AS _from0
        FROM SBIIMS_JXC_TJBB_CGYCGEntities.T_SPDW AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for WXDataDataModelStoreContainer.T_SPYS
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView10()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("WXDataDataModelStoreContainer.T_SPYS", @"
    SELECT VALUE -- Constructing T_SPYS
        [WX.Data.DataModel.Store.T_SPYS](T1.[T_SPYS.C_ID], T1.[T_SPYS.C_XH], T1.[T_SPYS.C_YS], T1.[T_SPYS.C_JYBZ], T1.[T_SPYS.C_XTCSBZ], T1.[T_SPYS.C_BZ])
    FROM (
        SELECT 
            T.C_ID AS [T_SPYS.C_ID], 
            T.C_XH AS [T_SPYS.C_XH], 
            T.C_YS AS [T_SPYS.C_YS], 
            T.C_JYBZ AS [T_SPYS.C_JYBZ], 
            T.C_XTCSBZ AS [T_SPYS.C_XTCSBZ], 
            T.C_BZ AS [T_SPYS.C_BZ], 
            True AS _from0
        FROM SBIIMS_JXC_TJBB_CGYCGEntities.T_SPYS AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for WXDataDataModelStoreContainer.T_YG
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView11()
        {
            System.Text.StringBuilder viewString = new System.Text.StringBuilder(2444);
            viewString.Append("\r\n    SELECT VALUE -- Constructing T_YG\r\n        [WX.Data.DataModel.Store.T_YG](");
            viewString.Append("T1.[T_YG.C_FBID], T1.[T_YG.C_GXRQ], T1.[T_YG.C_CJRQ], T1.[T_YG.C_ID], T1.[T_YG.C");
            viewString.Append("_XM], T1.[T_YG.C_XMJM], T1.[T_YG.C_XBH], T1.[T_YG.C_XB], T1.[T_YG.C_NL], T1.[T_Y");
            viewString.Append("G.C_XX], T1.[T_YG.C_XL], T1.[T_YG.C_HF], T1.[T_YG.C_ZN], T1.[T_YG.C_DWBM], T1.[T");
            viewString.Append("_YG.C_LXDH], T1.[T_YG.C_LXDZ], T1.[T_YG.C_JYBZ], T1.[T_YG.C_XTCSBZ], T1.[T_YG.C_");
            viewString.Append("XNBZ], T1.[T_YG.C_JBR], T1.[T_YG.C_CZY], T1.[T_YG.C_ZW], T1.[T_YG.C_GZJS], T1.[T");
            viewString.Append("_YG.C_TCBL], T1.[T_YG.C_GF], T1.[T_YG.C_RZRQ], T1.[T_YG.C_HTNX], T1.[T_YG.C_YLZB");
            viewString.Append("Z], T1.[T_YG.C_GZNX], T1.[T_YG.C_CZYBZ], T1.[T_YG.C_SHYBZ], T1.[T_YG.C_YWYBZ], T");
            viewString.Append("1.[T_YG.C_FZYW], T1.[T_YG.C_DWBMLJ], T1.[T_YG.C_BTFYX], T1.[T_YG.C_LZRQ], T1.[T_");
            viewString.Append("YG.C_ZP], T1.[T_YG.C_DY], T1.[T_YG.C_BZ])\r\n    FROM (\r\n        SELECT \r\n        ");
            viewString.Append("    T.C_FBID AS [T_YG.C_FBID], \r\n            T.C_GXRQ AS [T_YG.C_GXRQ], \r\n      ");
            viewString.Append("      T.C_CJRQ AS [T_YG.C_CJRQ], \r\n            T.C_ID AS [T_YG.C_ID], \r\n        ");
            viewString.Append("    T.C_XM AS [T_YG.C_XM], \r\n            T.C_XMJM AS [T_YG.C_XMJM], \r\n          ");
            viewString.Append("  T.C_XBH AS [T_YG.C_XBH], \r\n            T.C_XB AS [T_YG.C_XB], \r\n            T.");
            viewString.Append("C_NL AS [T_YG.C_NL], \r\n            T.C_XX AS [T_YG.C_XX], \r\n            T.C_XL A");
            viewString.Append("S [T_YG.C_XL], \r\n            T.C_HF AS [T_YG.C_HF], \r\n            T.C_ZN AS [T_Y");
            viewString.Append("G.C_ZN], \r\n            T.C_DWBM AS [T_YG.C_DWBM], \r\n            T.C_LXDH AS [T_Y");
            viewString.Append("G.C_LXDH], \r\n            T.C_LXDZ AS [T_YG.C_LXDZ], \r\n            T.C_JYBZ AS [T");
            viewString.Append("_YG.C_JYBZ], \r\n            T.C_XTCSBZ AS [T_YG.C_XTCSBZ], \r\n            T.C_XNBZ");
            viewString.Append(" AS [T_YG.C_XNBZ], \r\n            T.C_JBR AS [T_YG.C_JBR], \r\n            T.C_CZY ");
            viewString.Append("AS [T_YG.C_CZY], \r\n            T.C_ZW AS [T_YG.C_ZW], \r\n            T.C_GZJS AS ");
            viewString.Append("[T_YG.C_GZJS], \r\n            T.C_TCBL AS [T_YG.C_TCBL], \r\n            T.C_GF AS ");
            viewString.Append("[T_YG.C_GF], \r\n            T.C_RZRQ AS [T_YG.C_RZRQ], \r\n            T.C_HTNX AS ");
            viewString.Append("[T_YG.C_HTNX], \r\n            T.C_YLZBZ AS [T_YG.C_YLZBZ], \r\n            T.C_GZNX");
            viewString.Append(" AS [T_YG.C_GZNX], \r\n            T.C_CZYBZ AS [T_YG.C_CZYBZ], \r\n            T.C_");
            viewString.Append("SHYBZ AS [T_YG.C_SHYBZ], \r\n            T.C_YWYBZ AS [T_YG.C_YWYBZ], \r\n          ");
            viewString.Append("  T.C_FZYW AS [T_YG.C_FZYW], \r\n            T.C_DWBMLJ AS [T_YG.C_DWBMLJ], \r\n    ");
            viewString.Append("        T.C_BTFYX AS [T_YG.C_BTFYX], \r\n            T.C_LZRQ AS [T_YG.C_LZRQ], \r\n");
            viewString.Append("            T.C_ZP AS [T_YG.C_ZP], \r\n            T.C_DY AS [T_YG.C_DY], \r\n      ");
            viewString.Append("      T.C_BZ AS [T_YG.C_BZ], \r\n            True AS _from0\r\n        FROM SBIIMS_J");
            viewString.Append("XC_TJBB_CGYCGEntities.T_YG AS T\r\n    ) AS T1");
            return new System.Collections.Generic.KeyValuePair<string, string>("WXDataDataModelStoreContainer.T_YG", viewString.ToString());
        }
        
        /// <Summary>
        /// return view for SBIIMS_JXC_TJBB_CGYCGEntities.T_CK
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView12()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("SBIIMS_JXC_TJBB_CGYCGEntities.T_CK", @"
    SELECT VALUE -- Constructing T_CK
        [WX.Data.DataModel.T_CK](T1.[T_CK.C_FBID], T1.[T_CK.C_GXRQ], T1.[T_CK.C_CJRQ], T1.[T_CK.C_ID], T1.[T_CK.C_MC], T1.[T_CK.C_XBH], T1.[T_CK.C_MCJM], T1.[T_CK.C_FZR], T1.[T_CK.C_DQ], T1.[T_CK.C_DQLJ], T1.[T_CK.C_LXDH], T1.[T_CK.C_LXDZ], T1.[T_CK.C_MRBZ], T1.[T_CK.C_JYBZ], T1.[T_CK.C_XTCSBZ], T1.[T_CK.C_XNBZ], T1.[T_CK.C_CZY], T1.[T_CK.C_JBR], T1.[T_CK.C_BZ])
    FROM (
        SELECT 
            T.C_FBID AS [T_CK.C_FBID], 
            T.C_GXRQ AS [T_CK.C_GXRQ], 
            T.C_CJRQ AS [T_CK.C_CJRQ], 
            T.C_ID AS [T_CK.C_ID], 
            T.C_MC AS [T_CK.C_MC], 
            T.C_XBH AS [T_CK.C_XBH], 
            T.C_MCJM AS [T_CK.C_MCJM], 
            T.C_FZR AS [T_CK.C_FZR], 
            T.C_DQ AS [T_CK.C_DQ], 
            T.C_DQLJ AS [T_CK.C_DQLJ], 
            T.C_LXDH AS [T_CK.C_LXDH], 
            T.C_LXDZ AS [T_CK.C_LXDZ], 
            T.C_MRBZ AS [T_CK.C_MRBZ], 
            T.C_JYBZ AS [T_CK.C_JYBZ], 
            T.C_XTCSBZ AS [T_CK.C_XTCSBZ], 
            T.C_XNBZ AS [T_CK.C_XNBZ], 
            T.C_CZY AS [T_CK.C_CZY], 
            T.C_JBR AS [T_CK.C_JBR], 
            T.C_BZ AS [T_CK.C_BZ], 
            True AS _from0
        FROM WXDataDataModelStoreContainer.T_CK AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for SBIIMS_JXC_TJBB_CGYCGEntities.T_DJ_JHGL
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView13()
        {
            System.Text.StringBuilder viewString = new System.Text.StringBuilder(4220);
            viewString.Append("\r\n    SELECT VALUE -- Constructing T_DJ_JHGL\r\n        [WX.Data.DataModel.T_DJ_JH");
            viewString.Append("GL](T1.[T_DJ_JHGL.C_ZWYJSBZ], T1.[T_DJ_JHGL.C_ZWNJSBZ], T1.[T_DJ_JHGL.C_KDJQBZ],");
            viewString.Append(" T1.[T_DJ_JHGL.C_JQBZ], T1.[T_DJ_JHGL.C_CKBZ], T1.[T_DJ_JHGL.C_RKBZ], T1.[T_DJ_J");
            viewString.Append("HGL.C_YSBZ], T1.[T_DJ_JHGL.C_HLPCBZ], T1.[T_DJ_JHGL.C_JQRQ], T1.[T_DJ_JHGL.C_ZWY");
            viewString.Append("], T1.[T_DJ_JHGL.C_ZWN], T1.[T_DJ_JHGL.C_FBID], T1.[T_DJ_JHGL.C_GXRQ], T1.[T_DJ_");
            viewString.Append("JHGL.C_CJRQ], T1.[T_DJ_JHGL.C_SJYRQ], T1.[T_DJ_JHGL.C_ID], T1.[T_DJ_JHGL.C_DJH],");
            viewString.Append(" T1.[T_DJ_JHGL.C_DJLX], T1.[T_DJ_JHGL.C_WFDW], T1.[T_DJ_JHGL.C_GHS], T1.[T_DJ_JH");
            viewString.Append("GL.C_GHSJBR], T1.[T_DJ_JHGL.C_CCK], T1.[T_DJ_JHGL.C_RCK], T1.[T_DJ_JHGL.C_YZQJE]");
            viewString.Append(", T1.[T_DJ_JHGL.C_DJYZQJE], T1.[T_DJ_JHGL.C_DJSZQJE], T1.[T_DJ_JHGL.C_DJYHJE], T");
            viewString.Append("1.[T_DJ_JHGL.C_VDJYZQJE], T1.[T_DJ_JHGL.C_VDJSZQJE], T1.[T_DJ_JHGL.C_VDJYHJE], T");
            viewString.Append("1.[T_DJ_JHGL.C_SZQJE], T1.[T_DJ_JHGL.C_JBR], T1.[T_DJ_JHGL.C_CZY], T1.[T_DJ_JHGL");
            viewString.Append(".C_DYBZ], T1.[T_DJ_JHGL.C_THBZ], T1.[T_DJ_JHGL.C_DJZT], T1.[T_DJ_JHGL.C_CKSL], T");
            viewString.Append("1.[T_DJ_JHGL.C_RKSL], T1.[T_DJ_JHGL.C_CKJE], T1.[T_DJ_JHGL.C_RKJE], T1.[T_DJ_JHG");
            viewString.Append("L.C_CKCBJE], T1.[T_DJ_JHGL.C_RKCBJE], T1.[T_DJ_JHGL.C_DJLRJE], T1.[T_DJ_JHGL.C_D");
            viewString.Append("JJYLRL], T1.[T_DJ_JHGL.C_DJCBLRL], T1.[T_DJ_JHGL.C_SPYHJE], T1.[T_DJ_JHGL.C_DJTM");
            viewString.Append("SL], T1.[T_DJ_JHGL.C_WFYHZH], T1.[T_DJ_JHGL.C_GHSYHZH], T1.[T_DJ_JHGL.C_WFZHLB],");
            viewString.Append(" T1.[T_DJ_JHGL.C_GHSZHLB], T1.[T_DJ_JHGL.C_ZFFS], T1.[T_DJ_JHGL.C_GLDJ], T1.[T_D");
            viewString.Append("J_JHGL.C_SHR], T1.[T_DJ_JHGL.C_GLDJH], T1.[T_DJ_JHGL.C_BZ])\r\n    FROM (\r\n       ");
            viewString.Append(" SELECT \r\n            T.C_ZWYJSBZ AS [T_DJ_JHGL.C_ZWYJSBZ], \r\n            T.C_ZW");
            viewString.Append("NJSBZ AS [T_DJ_JHGL.C_ZWNJSBZ], \r\n            T.C_KDJQBZ AS [T_DJ_JHGL.C_KDJQBZ]");
            viewString.Append(", \r\n            T.C_JQBZ AS [T_DJ_JHGL.C_JQBZ], \r\n            T.C_CKBZ AS [T_DJ_");
            viewString.Append("JHGL.C_CKBZ], \r\n            T.C_RKBZ AS [T_DJ_JHGL.C_RKBZ], \r\n            T.C_YS");
            viewString.Append("BZ AS [T_DJ_JHGL.C_YSBZ], \r\n            T.C_HLPCBZ AS [T_DJ_JHGL.C_HLPCBZ], \r\n  ");
            viewString.Append("          T.C_JQRQ AS [T_DJ_JHGL.C_JQRQ], \r\n            T.C_ZWY AS [T_DJ_JHGL.C_");
            viewString.Append("ZWY], \r\n            T.C_ZWN AS [T_DJ_JHGL.C_ZWN], \r\n            T.C_FBID AS [T_D");
            viewString.Append("J_JHGL.C_FBID], \r\n            T.C_GXRQ AS [T_DJ_JHGL.C_GXRQ], \r\n            T.C_");
            viewString.Append("CJRQ AS [T_DJ_JHGL.C_CJRQ], \r\n            T.C_SJYRQ AS [T_DJ_JHGL.C_SJYRQ], \r\n  ");
            viewString.Append("          T.C_ID AS [T_DJ_JHGL.C_ID], \r\n            T.C_DJH AS [T_DJ_JHGL.C_DJH]");
            viewString.Append(", \r\n            T.C_DJLX AS [T_DJ_JHGL.C_DJLX], \r\n            T.C_WFDW AS [T_DJ_");
            viewString.Append("JHGL.C_WFDW], \r\n            T.C_GHS AS [T_DJ_JHGL.C_GHS], \r\n            T.C_GHSJ");
            viewString.Append("BR AS [T_DJ_JHGL.C_GHSJBR], \r\n            T.C_CCK AS [T_DJ_JHGL.C_CCK], \r\n      ");
            viewString.Append("      T.C_RCK AS [T_DJ_JHGL.C_RCK], \r\n            T.C_YZQJE AS [T_DJ_JHGL.C_YZQJ");
            viewString.Append("E], \r\n            T.C_DJYZQJE AS [T_DJ_JHGL.C_DJYZQJE], \r\n            T.C_DJSZQJ");
            viewString.Append("E AS [T_DJ_JHGL.C_DJSZQJE], \r\n            T.C_DJYHJE AS [T_DJ_JHGL.C_DJYHJE], \r\n");
            viewString.Append("            T.C_VDJYZQJE AS [T_DJ_JHGL.C_VDJYZQJE], \r\n            T.C_VDJSZQJE A");
            viewString.Append("S [T_DJ_JHGL.C_VDJSZQJE], \r\n            T.C_VDJYHJE AS [T_DJ_JHGL.C_VDJYHJE], \r\n");
            viewString.Append("            T.C_SZQJE AS [T_DJ_JHGL.C_SZQJE], \r\n            T.C_JBR AS [T_DJ_JHG");
            viewString.Append("L.C_JBR], \r\n            T.C_CZY AS [T_DJ_JHGL.C_CZY], \r\n            T.C_DYBZ AS ");
            viewString.Append("[T_DJ_JHGL.C_DYBZ], \r\n            T.C_THBZ AS [T_DJ_JHGL.C_THBZ], \r\n            ");
            viewString.Append("T.C_DJZT AS [T_DJ_JHGL.C_DJZT], \r\n            T.C_CKSL AS [T_DJ_JHGL.C_CKSL], \r\n");
            viewString.Append("            T.C_RKSL AS [T_DJ_JHGL.C_RKSL], \r\n            T.C_CKJE AS [T_DJ_JHGL");
            viewString.Append(".C_CKJE], \r\n            T.C_RKJE AS [T_DJ_JHGL.C_RKJE], \r\n            T.C_CKCBJE");
            viewString.Append(" AS [T_DJ_JHGL.C_CKCBJE], \r\n            T.C_RKCBJE AS [T_DJ_JHGL.C_RKCBJE], \r\n  ");
            viewString.Append("          T.C_DJLRJE AS [T_DJ_JHGL.C_DJLRJE], \r\n            T.C_DJJYLRL AS [T_DJ");
            viewString.Append("_JHGL.C_DJJYLRL], \r\n            T.C_DJCBLRL AS [T_DJ_JHGL.C_DJCBLRL], \r\n        ");
            viewString.Append("    T.C_SPYHJE AS [T_DJ_JHGL.C_SPYHJE], \r\n            T.C_DJTMSL AS [T_DJ_JHGL.C");
            viewString.Append("_DJTMSL], \r\n            T.C_WFYHZH AS [T_DJ_JHGL.C_WFYHZH], \r\n            T.C_GH");
            viewString.Append("SYHZH AS [T_DJ_JHGL.C_GHSYHZH], \r\n            T.C_WFZHLB AS [T_DJ_JHGL.C_WFZHLB]");
            viewString.Append(", \r\n            T.C_GHSZHLB AS [T_DJ_JHGL.C_GHSZHLB], \r\n            T.C_ZFFS AS ");
            viewString.Append("[T_DJ_JHGL.C_ZFFS], \r\n            T.C_GLDJ AS [T_DJ_JHGL.C_GLDJ], \r\n            ");
            viewString.Append("T.C_SHR AS [T_DJ_JHGL.C_SHR], \r\n            T.C_GLDJH AS [T_DJ_JHGL.C_GLDJH], \r\n");
            viewString.Append("            T.C_BZ AS [T_DJ_JHGL.C_BZ], \r\n            True AS _from0\r\n        FR");
            viewString.Append("OM WXDataDataModelStoreContainer.T_DJ_JHGL AS T\r\n    ) AS T1");
            return new System.Collections.Generic.KeyValuePair<string, string>("SBIIMS_JXC_TJBB_CGYCGEntities.T_DJ_JHGL", viewString.ToString());
        }
        
        /// <Summary>
        /// return view for SBIIMS_JXC_TJBB_CGYCGEntities.T_DJLX
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView14()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("SBIIMS_JXC_TJBB_CGYCGEntities.T_DJLX", @"
    SELECT VALUE -- Constructing T_DJLX
        [WX.Data.DataModel.T_DJLX](T1.[T_DJLX.C_DM], T1.[T_DJLX.C_LX], T1.[T_DJLX.C_QZ], T1.[T_DJLX.C_LB], T1.[T_DJLX.C_JYBZ], T1.[T_DJLX.C_BZ])
    FROM (
        SELECT 
            T.C_DM AS [T_DJLX.C_DM], 
            T.C_LX AS [T_DJLX.C_LX], 
            T.C_QZ AS [T_DJLX.C_QZ], 
            T.C_LB AS [T_DJLX.C_LB], 
            T.C_JYBZ AS [T_DJLX.C_JYBZ], 
            T.C_BZ AS [T_DJLX.C_BZ], 
            True AS _from0
        FROM WXDataDataModelStoreContainer.T_DJLX AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for SBIIMS_JXC_TJBB_CGYCGEntities.T_DJSP_JHGL
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView15()
        {
            System.Text.StringBuilder viewString = new System.Text.StringBuilder(3342);
            viewString.Append("\r\n    SELECT VALUE -- Constructing T_DJSP_JHGL\r\n        [WX.Data.DataModel.T_DJS");
            viewString.Append("P_JHGL](T1.[T_DJSP_JHGL.C_ZWYJSBZ], T1.[T_DJSP_JHGL.C_ZWNJSBZ], T1.[T_DJSP_JHGL.");
            viewString.Append("C_CKBZ], T1.[T_DJSP_JHGL.C_RKBZ], T1.[T_DJSP_JHGL.C_HLPCBZ], T1.[T_DJSP_JHGL.C_Z");
            viewString.Append("WY], T1.[T_DJSP_JHGL.C_ZWN], T1.[T_DJSP_JHGL.C_FBID], T1.[T_DJSP_JHGL.C_CJRQ], T");
            viewString.Append("1.[T_DJSP_JHGL.C_ID], T1.[T_DJSP_JHGL.C_DJID], T1.[T_DJSP_JHGL.C_SP], T1.[T_DJSP");
            viewString.Append("_JHGL.C_PC], T1.[T_DJSP_JHGL.C_XH], T1.[T_DJSP_JHGL.C_SCRQ], T1.[T_DJSP_JHGL.C_Y");
            viewString.Append("XRQ], T1.[T_DJSP_JHGL.C_SPPH], T1.[T_DJSP_JHGL.C_JJ], T1.[T_DJSP_JHGL.C_DJ], T1.");
            viewString.Append("[T_DJSP_JHGL.C_ZKL], T1.[T_DJSP_JHGL.C_ZHJ], T1.[T_DJSP_JHGL.C_SL], T1.[T_DJSP_J");
            viewString.Append("HGL.C_ZJE], T1.[T_DJSP_JHGL.C_ZHJE], T1.[T_DJSP_JHGL.C_VSL], T1.[T_DJSP_JHGL.C_V");
            viewString.Append("ZJE], T1.[T_DJSP_JHGL.C_VZHJE], T1.[T_DJSP_JHGL.C_CBJE], T1.[T_DJSP_JHGL.C_VCBJE");
            viewString.Append("], T1.[T_DJSP_JHGL.C_CGGHS], T1.[T_DJSP_JHGL.C_SPLRJE], T1.[T_DJSP_JHGL.C_SPJYLR");
            viewString.Append("L], T1.[T_DJSP_JHGL.C_SPCBLRL], T1.[T_DJSP_JHGL.C_SPYHJE], T1.[T_DJSP_JHGL.C_DJH");
            viewString.Append("], T1.[T_DJSP_JHGL.C_DJLX], T1.[T_DJSP_JHGL.C_CCK], T1.[T_DJSP_JHGL.C_RCK], T1.[");
            viewString.Append("T_DJSP_JHGL.C_JBR], T1.[T_DJSP_JHGL.C_CZY], T1.[T_DJSP_JHGL.C_CGDJID], T1.[T_DJS");
            viewString.Append("P_JHGL.C_SHR], T1.[T_DJSP_JHGL.C_BZ])\r\n    FROM (\r\n        SELECT \r\n            ");
            viewString.Append("T.C_ZWYJSBZ AS [T_DJSP_JHGL.C_ZWYJSBZ], \r\n            T.C_ZWNJSBZ AS [T_DJSP_JHG");
            viewString.Append("L.C_ZWNJSBZ], \r\n            T.C_CKBZ AS [T_DJSP_JHGL.C_CKBZ], \r\n            T.C_");
            viewString.Append("RKBZ AS [T_DJSP_JHGL.C_RKBZ], \r\n            T.C_HLPCBZ AS [T_DJSP_JHGL.C_HLPCBZ]");
            viewString.Append(", \r\n            T.C_ZWY AS [T_DJSP_JHGL.C_ZWY], \r\n            T.C_ZWN AS [T_DJSP");
            viewString.Append("_JHGL.C_ZWN], \r\n            T.C_FBID AS [T_DJSP_JHGL.C_FBID], \r\n            T.C_");
            viewString.Append("CJRQ AS [T_DJSP_JHGL.C_CJRQ], \r\n            T.C_ID AS [T_DJSP_JHGL.C_ID], \r\n    ");
            viewString.Append("        T.C_DJID AS [T_DJSP_JHGL.C_DJID], \r\n            T.C_SP AS [T_DJSP_JHGL.C");
            viewString.Append("_SP], \r\n            T.C_PC AS [T_DJSP_JHGL.C_PC], \r\n            T.C_XH AS [T_DJS");
            viewString.Append("P_JHGL.C_XH], \r\n            T.C_SCRQ AS [T_DJSP_JHGL.C_SCRQ], \r\n            T.C_");
            viewString.Append("YXRQ AS [T_DJSP_JHGL.C_YXRQ], \r\n            T.C_SPPH AS [T_DJSP_JHGL.C_SPPH], \r\n");
            viewString.Append("            T.C_JJ AS [T_DJSP_JHGL.C_JJ], \r\n            T.C_DJ AS [T_DJSP_JHGL.C");
            viewString.Append("_DJ], \r\n            T.C_ZKL AS [T_DJSP_JHGL.C_ZKL], \r\n            T.C_ZHJ AS [T_");
            viewString.Append("DJSP_JHGL.C_ZHJ], \r\n            T.C_SL AS [T_DJSP_JHGL.C_SL], \r\n            T.C_");
            viewString.Append("ZJE AS [T_DJSP_JHGL.C_ZJE], \r\n            T.C_ZHJE AS [T_DJSP_JHGL.C_ZHJE], \r\n  ");
            viewString.Append("          T.C_VSL AS [T_DJSP_JHGL.C_VSL], \r\n            T.C_VZJE AS [T_DJSP_JHGL");
            viewString.Append(".C_VZJE], \r\n            T.C_VZHJE AS [T_DJSP_JHGL.C_VZHJE], \r\n            T.C_CB");
            viewString.Append("JE AS [T_DJSP_JHGL.C_CBJE], \r\n            T.C_VCBJE AS [T_DJSP_JHGL.C_VCBJE], \r\n");
            viewString.Append("            T.C_CGGHS AS [T_DJSP_JHGL.C_CGGHS], \r\n            T.C_SPLRJE AS [T_D");
            viewString.Append("JSP_JHGL.C_SPLRJE], \r\n            T.C_SPJYLRL AS [T_DJSP_JHGL.C_SPJYLRL], \r\n    ");
            viewString.Append("        T.C_SPCBLRL AS [T_DJSP_JHGL.C_SPCBLRL], \r\n            T.C_SPYHJE AS [T_D");
            viewString.Append("JSP_JHGL.C_SPYHJE], \r\n            T.C_DJH AS [T_DJSP_JHGL.C_DJH], \r\n            ");
            viewString.Append("T.C_DJLX AS [T_DJSP_JHGL.C_DJLX], \r\n            T.C_CCK AS [T_DJSP_JHGL.C_CCK], ");
            viewString.Append("\r\n            T.C_RCK AS [T_DJSP_JHGL.C_RCK], \r\n            T.C_JBR AS [T_DJSP_J");
            viewString.Append("HGL.C_JBR], \r\n            T.C_CZY AS [T_DJSP_JHGL.C_CZY], \r\n            T.C_CGDJ");
            viewString.Append("ID AS [T_DJSP_JHGL.C_CGDJID], \r\n            T.C_SHR AS [T_DJSP_JHGL.C_SHR], \r\n  ");
            viewString.Append("          T.C_BZ AS [T_DJSP_JHGL.C_BZ], \r\n            True AS _from0\r\n        FR");
            viewString.Append("OM WXDataDataModelStoreContainer.T_DJSP_JHGL AS T\r\n    ) AS T1");
            return new System.Collections.Generic.KeyValuePair<string, string>("SBIIMS_JXC_TJBB_CGYCGEntities.T_DJSP_JHGL", viewString.ToString());
        }
        
        /// <Summary>
        /// return view for SBIIMS_JXC_TJBB_CGYCGEntities.T_GHS
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView16()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("SBIIMS_JXC_TJBB_CGYCGEntities.T_GHS", "\r\n    SELECT VALUE -- Constructing T_GHS\r\n        [WX.Data.DataModel.T_GHS](T1.[T" +
                    "_GHS.C_FBID], T1.[T_GHS.C_GXRQ], T1.[T_GHS.C_CJRQ], T1.[T_GHS.C_ID], T1.[T_GHS.C" +
                    "_MC], T1.[T_GHS.C_MCJM], T1.[T_GHS.C_XBH], T1.[T_GHS.C_LB], T1.[T_GHS.C_LX], T1." +
                    "[T_GHS.C_DJ], T1.[T_GHS.C_LXDH], T1.[T_GHS.C_LXDZ], T1.[T_GHS.C_XYJF], T1.[T_GHS" +
                    ".C_GHJF], T1.[T_GHS.C_DQ], T1.[T_GHS.C_MRBZ], T1.[T_GHS.C_JYBZ], T1.[T_GHS.C_XTC" +
                    "SBZ], T1.[T_GHS.C_XNBZ], T1.[T_GHS.C_CZY], T1.[T_GHS.C_JBR], T1.[T_GHS.C_LXR], T" +
                    "1.[T_GHS.C_DY], T1.[T_GHS.C_BZ])\r\n    FROM (\r\n        SELECT \r\n            T.C_F" +
                    "BID AS [T_GHS.C_FBID], \r\n            T.C_GXRQ AS [T_GHS.C_GXRQ], \r\n            T" +
                    ".C_CJRQ AS [T_GHS.C_CJRQ], \r\n            T.C_ID AS [T_GHS.C_ID], \r\n            T" +
                    ".C_MC AS [T_GHS.C_MC], \r\n            T.C_MCJM AS [T_GHS.C_MCJM], \r\n            T" +
                    ".C_XBH AS [T_GHS.C_XBH], \r\n            T.C_LB AS [T_GHS.C_LB], \r\n            T.C" +
                    "_LX AS [T_GHS.C_LX], \r\n            T.C_DJ AS [T_GHS.C_DJ], \r\n            T.C_LXD" +
                    "H AS [T_GHS.C_LXDH], \r\n            T.C_LXDZ AS [T_GHS.C_LXDZ], \r\n            T.C" +
                    "_XYJF AS [T_GHS.C_XYJF], \r\n            T.C_GHJF AS [T_GHS.C_GHJF], \r\n           " +
                    " T.C_DQ AS [T_GHS.C_DQ], \r\n            T.C_MRBZ AS [T_GHS.C_MRBZ], \r\n           " +
                    " T.C_JYBZ AS [T_GHS.C_JYBZ], \r\n            T.C_XTCSBZ AS [T_GHS.C_XTCSBZ], \r\n   " +
                    "         T.C_XNBZ AS [T_GHS.C_XNBZ], \r\n            T.C_CZY AS [T_GHS.C_CZY], \r\n " +
                    "           T.C_JBR AS [T_GHS.C_JBR], \r\n            T.C_LXR AS [T_GHS.C_LXR], \r\n " +
                    "           T.C_DY AS [T_GHS.C_DY], \r\n            T.C_BZ AS [T_GHS.C_BZ], \r\n     " +
                    "       True AS _from0\r\n        FROM WXDataDataModelStoreContainer.T_GHS AS T\r\n  " +
                    "  ) AS T1");
        }
        
        /// <Summary>
        /// return view for SBIIMS_JXC_TJBB_CGYCGEntities.T_KCSP_DQZT
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView17()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("SBIIMS_JXC_TJBB_CGYCGEntities.T_KCSP_DQZT", @"
    SELECT VALUE -- Constructing T_KCSP_DQZT
        [WX.Data.DataModel.T_KCSP_DQZT](T1.[T_KCSP_DQZT.C_FBID], T1.[T_KCSP_DQZT.C_GXRQ], T1.[T_KCSP_DQZT.C_CJRQ], T1.[T_KCSP_DQZT.C_KCSP], T1.[T_KCSP_DQZT.C_KCSL], T1.[T_KCSP_DQZT.C_KCSX], T1.[T_KCSP_DQZT.C_KCXX], T1.[T_KCSP_DQZT.C_CBJJ], T1.[T_KCSP_DQZT.C_SCJJ], T1.[T_KCSP_DQZT.C_CBJE], T1.[T_KCSP_DQZT.C_RKSL], T1.[T_KCSP_DQZT.C_CKSL])
    FROM (
        SELECT 
            T.C_FBID AS [T_KCSP_DQZT.C_FBID], 
            T.C_GXRQ AS [T_KCSP_DQZT.C_GXRQ], 
            T.C_CJRQ AS [T_KCSP_DQZT.C_CJRQ], 
            T.C_KCSP AS [T_KCSP_DQZT.C_KCSP], 
            T.C_KCSL AS [T_KCSP_DQZT.C_KCSL], 
            T.C_KCSX AS [T_KCSP_DQZT.C_KCSX], 
            T.C_KCXX AS [T_KCSP_DQZT.C_KCXX], 
            T.C_CBJJ AS [T_KCSP_DQZT.C_CBJJ], 
            T.C_SCJJ AS [T_KCSP_DQZT.C_SCJJ], 
            T.C_CBJE AS [T_KCSP_DQZT.C_CBJE], 
            T.C_RKSL AS [T_KCSP_DQZT.C_RKSL], 
            T.C_CKSL AS [T_KCSP_DQZT.C_CKSL], 
            True AS _from0
        FROM WXDataDataModelStoreContainer.T_KCSP_DQZT AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for SBIIMS_JXC_TJBB_CGYCGEntities.T_QFMX_JHGL
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView18()
        {
            System.Text.StringBuilder viewString = new System.Text.StringBuilder(3380);
            viewString.Append("\r\n    SELECT VALUE -- Constructing T_QFMX_JHGL\r\n        [WX.Data.DataModel.T_QFM");
            viewString.Append("X_JHGL](T1.[T_QFMX_JHGL.C_CKBZ], T1.[T_QFMX_JHGL.C_RKBZ], T1.[T_QFMX_JHGL.C_QSBZ");
            viewString.Append("], T1.[T_QFMX_JHGL.C_ZWNJSBZ], T1.[T_QFMX_JHGL.C_ZWYJSBZ], T1.[T_QFMX_JHGL.C_ZWN");
            viewString.Append("], T1.[T_QFMX_JHGL.C_ZWY], T1.[T_QFMX_JHGL.C_FBID], T1.[T_QFMX_JHGL.C_GXRQ], T1.");
            viewString.Append("[T_QFMX_JHGL.C_CJRQ], T1.[T_QFMX_JHGL.C_QFJE], T1.[T_QFMX_JHGL.C_SZQJE], T1.[T_Q");
            viewString.Append("FMX_JHGL.C_DJ], T1.[T_QFMX_JHGL.C_DJH], T1.[T_QFMX_JHGL.C_DJLX], T1.[T_QFMX_JHGL");
            viewString.Append(".C_GHS], T1.[T_QFMX_JHGL.C_GHSJBR], T1.[T_QFMX_JHGL.C_YZQJE], T1.[T_QFMX_JHGL.C_");
            viewString.Append("DJYZQJE], T1.[T_QFMX_JHGL.C_DJSZQJE], T1.[T_QFMX_JHGL.C_DJYHJE], T1.[T_QFMX_JHGL");
            viewString.Append(".C_VDJYZQJE], T1.[T_QFMX_JHGL.C_VDJSZQJE], T1.[T_QFMX_JHGL.C_VDJYHJE], T1.[T_QFM");
            viewString.Append("X_JHGL.C_CCK], T1.[T_QFMX_JHGL.C_RCK], T1.[T_QFMX_JHGL.C_CKSL], T1.[T_QFMX_JHGL.");
            viewString.Append("C_RKSL], T1.[T_QFMX_JHGL.C_CKJE], T1.[T_QFMX_JHGL.C_RKJE], T1.[T_QFMX_JHGL.C_CKC");
            viewString.Append("BJE], T1.[T_QFMX_JHGL.C_RKCBJE], T1.[T_QFMX_JHGL.C_JBR], T1.[T_QFMX_JHGL.C_CZY],");
            viewString.Append(" T1.[T_QFMX_JHGL.C_DJLRJE], T1.[T_QFMX_JHGL.C_DJJYLRL], T1.[T_QFMX_JHGL.C_DJCBLR");
            viewString.Append("L], T1.[T_QFMX_JHGL.C_SPYHJE], T1.[T_QFMX_JHGL.C_DJTMSL], T1.[T_QFMX_JHGL.C_GLDJ");
            viewString.Append("], T1.[T_QFMX_JHGL.C_SHR], T1.[T_QFMX_JHGL.C_BZ])\r\n    FROM (\r\n        SELECT \r\n");
            viewString.Append("            T.C_CKBZ AS [T_QFMX_JHGL.C_CKBZ], \r\n            T.C_RKBZ AS [T_QFMX_");
            viewString.Append("JHGL.C_RKBZ], \r\n            T.C_QSBZ AS [T_QFMX_JHGL.C_QSBZ], \r\n            T.C_");
            viewString.Append("ZWNJSBZ AS [T_QFMX_JHGL.C_ZWNJSBZ], \r\n            T.C_ZWYJSBZ AS [T_QFMX_JHGL.C_");
            viewString.Append("ZWYJSBZ], \r\n            T.C_ZWN AS [T_QFMX_JHGL.C_ZWN], \r\n            T.C_ZWY AS");
            viewString.Append(" [T_QFMX_JHGL.C_ZWY], \r\n            T.C_FBID AS [T_QFMX_JHGL.C_FBID], \r\n        ");
            viewString.Append("    T.C_GXRQ AS [T_QFMX_JHGL.C_GXRQ], \r\n            T.C_CJRQ AS [T_QFMX_JHGL.C_C");
            viewString.Append("JRQ], \r\n            T.C_QFJE AS [T_QFMX_JHGL.C_QFJE], \r\n            T.C_SZQJE AS");
            viewString.Append(" [T_QFMX_JHGL.C_SZQJE], \r\n            T.C_DJ AS [T_QFMX_JHGL.C_DJ], \r\n          ");
            viewString.Append("  T.C_DJH AS [T_QFMX_JHGL.C_DJH], \r\n            T.C_DJLX AS [T_QFMX_JHGL.C_DJLX]");
            viewString.Append(", \r\n            T.C_GHS AS [T_QFMX_JHGL.C_GHS], \r\n            T.C_GHSJBR AS [T_Q");
            viewString.Append("FMX_JHGL.C_GHSJBR], \r\n            T.C_YZQJE AS [T_QFMX_JHGL.C_YZQJE], \r\n        ");
            viewString.Append("    T.C_DJYZQJE AS [T_QFMX_JHGL.C_DJYZQJE], \r\n            T.C_DJSZQJE AS [T_QFMX");
            viewString.Append("_JHGL.C_DJSZQJE], \r\n            T.C_DJYHJE AS [T_QFMX_JHGL.C_DJYHJE], \r\n        ");
            viewString.Append("    T.C_VDJYZQJE AS [T_QFMX_JHGL.C_VDJYZQJE], \r\n            T.C_VDJSZQJE AS [T_Q");
            viewString.Append("FMX_JHGL.C_VDJSZQJE], \r\n            T.C_VDJYHJE AS [T_QFMX_JHGL.C_VDJYHJE], \r\n  ");
            viewString.Append("          T.C_CCK AS [T_QFMX_JHGL.C_CCK], \r\n            T.C_RCK AS [T_QFMX_JHGL.");
            viewString.Append("C_RCK], \r\n            T.C_CKSL AS [T_QFMX_JHGL.C_CKSL], \r\n            T.C_RKSL A");
            viewString.Append("S [T_QFMX_JHGL.C_RKSL], \r\n            T.C_CKJE AS [T_QFMX_JHGL.C_CKJE], \r\n      ");
            viewString.Append("      T.C_RKJE AS [T_QFMX_JHGL.C_RKJE], \r\n            T.C_CKCBJE AS [T_QFMX_JHGL");
            viewString.Append(".C_CKCBJE], \r\n            T.C_RKCBJE AS [T_QFMX_JHGL.C_RKCBJE], \r\n            T.");
            viewString.Append("C_JBR AS [T_QFMX_JHGL.C_JBR], \r\n            T.C_CZY AS [T_QFMX_JHGL.C_CZY], \r\n  ");
            viewString.Append("          T.C_DJLRJE AS [T_QFMX_JHGL.C_DJLRJE], \r\n            T.C_DJJYLRL AS [T_");
            viewString.Append("QFMX_JHGL.C_DJJYLRL], \r\n            T.C_DJCBLRL AS [T_QFMX_JHGL.C_DJCBLRL], \r\n  ");
            viewString.Append("          T.C_SPYHJE AS [T_QFMX_JHGL.C_SPYHJE], \r\n            T.C_DJTMSL AS [T_Q");
            viewString.Append("FMX_JHGL.C_DJTMSL], \r\n            T.C_GLDJ AS [T_QFMX_JHGL.C_GLDJ], \r\n          ");
            viewString.Append("  T.C_SHR AS [T_QFMX_JHGL.C_SHR], \r\n            T.C_BZ AS [T_QFMX_JHGL.C_BZ], \r\n");
            viewString.Append("            True AS _from0\r\n        FROM WXDataDataModelStoreContainer.T_QFMX_JH");
            viewString.Append("GL AS T\r\n    ) AS T1");
            return new System.Collections.Generic.KeyValuePair<string, string>("SBIIMS_JXC_TJBB_CGYCGEntities.T_QFMX_JHGL", viewString.ToString());
        }
        
        /// <Summary>
        /// return view for SBIIMS_JXC_TJBB_CGYCGEntities.T_RZ
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView19()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("SBIIMS_JXC_TJBB_CGYCGEntities.T_RZ", @"
    SELECT VALUE -- Constructing T_RZ
        [WX.Data.DataModel.T_RZ](T1.[T_RZ.C_FBID], T1.[T_RZ.C_CJRQ], T1.[T_RZ.C_ID], T1.[T_RZ.C_JLID], T1.[T_RZ.C_YWLX], T1.[T_RZ.C_YWLXMC], T1.[T_RZ.C_CZLX], T1.[T_RZ.C_CZLXMC], T1.[T_RZ.C_CZY], T1.[T_RZ.C_CZYXM], T1.[T_RZ.C_BM], T1.[T_RZ.C_BBM], T1.[T_RZ.C_ZBM], T1.[T_RZ.C_ZBBM], T1.[T_RZ.C_ZBSL], T1.[T_RZ.C_HOST], T1.[T_RZ.C_IP], T1.[T_RZ.C_NR])
    FROM (
        SELECT 
            T.C_FBID AS [T_RZ.C_FBID], 
            T.C_CJRQ AS [T_RZ.C_CJRQ], 
            T.C_ID AS [T_RZ.C_ID], 
            T.C_JLID AS [T_RZ.C_JLID], 
            T.C_YWLX AS [T_RZ.C_YWLX], 
            T.C_YWLXMC AS [T_RZ.C_YWLXMC], 
            T.C_CZLX AS [T_RZ.C_CZLX], 
            T.C_CZLXMC AS [T_RZ.C_CZLXMC], 
            T.C_CZY AS [T_RZ.C_CZY], 
            T.C_CZYXM AS [T_RZ.C_CZYXM], 
            T.C_BM AS [T_RZ.C_BM], 
            T.C_BBM AS [T_RZ.C_BBM], 
            T.C_ZBM AS [T_RZ.C_ZBM], 
            T.C_ZBBM AS [T_RZ.C_ZBBM], 
            T.C_ZBSL AS [T_RZ.C_ZBSL], 
            T.C_HOST AS [T_RZ.C_HOST], 
            T.C_IP AS [T_RZ.C_IP], 
            T.C_NR AS [T_RZ.C_NR], 
            True AS _from0
        FROM WXDataDataModelStoreContainer.T_RZ AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for SBIIMS_JXC_TJBB_CGYCGEntities.T_SP
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView20()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("SBIIMS_JXC_TJBB_CGYCGEntities.T_SP", "\r\n    SELECT VALUE -- Constructing T_SP\r\n        [WX.Data.DataModel.T_SP](T1.[T_S" +
                    "P.C_JYBZ], T1.[T_SP.C_XNBZ], T1.[T_SP.C_XTCSBZ], T1.[T_SP.C_FBID], T1.[T_SP.C_ID" +
                    "], T1.[T_SP.C_GXRQ], T1.[T_SP.C_CJRQ], T1.[T_SP.C_XBH], T1.[T_SP.C_MC], T1.[T_SP" +
                    ".C_MCJM], T1.[T_SP.C_DW], T1.[T_SP.C_GGXH], T1.[T_SP.C_YS], T1.[T_SP.C_SPLB], T1" +
                    ".[T_SP.C_SCCS], T1.[T_SP.C_KCSX], T1.[T_SP.C_KCXX], T1.[T_SP.C_YSJJ], T1.[T_SP.C" +
                    "_YSSJ], T1.[T_SP.C_BZQX], T1.[T_SP.C_BHQX], T1.[T_SP.C_CZY], T1.[T_SP.C_JBR], T1" +
                    ".[T_SP.C_TM], T1.[T_SP.C_BZ])\r\n    FROM (\r\n        SELECT \r\n            T.C_JYBZ" +
                    " AS [T_SP.C_JYBZ], \r\n            T.C_XNBZ AS [T_SP.C_XNBZ], \r\n            T.C_XT" +
                    "CSBZ AS [T_SP.C_XTCSBZ], \r\n            T.C_FBID AS [T_SP.C_FBID], \r\n            " +
                    "T.C_ID AS [T_SP.C_ID], \r\n            T.C_GXRQ AS [T_SP.C_GXRQ], \r\n            T." +
                    "C_CJRQ AS [T_SP.C_CJRQ], \r\n            T.C_XBH AS [T_SP.C_XBH], \r\n            T." +
                    "C_MC AS [T_SP.C_MC], \r\n            T.C_MCJM AS [T_SP.C_MCJM], \r\n            T.C_" +
                    "DW AS [T_SP.C_DW], \r\n            T.C_GGXH AS [T_SP.C_GGXH], \r\n            T.C_YS" +
                    " AS [T_SP.C_YS], \r\n            T.C_SPLB AS [T_SP.C_SPLB], \r\n            T.C_SCCS" +
                    " AS [T_SP.C_SCCS], \r\n            T.C_KCSX AS [T_SP.C_KCSX], \r\n            T.C_KC" +
                    "XX AS [T_SP.C_KCXX], \r\n            T.C_YSJJ AS [T_SP.C_YSJJ], \r\n            T.C_" +
                    "YSSJ AS [T_SP.C_YSSJ], \r\n            T.C_BZQX AS [T_SP.C_BZQX], \r\n            T." +
                    "C_BHQX AS [T_SP.C_BHQX], \r\n            T.C_CZY AS [T_SP.C_CZY], \r\n            T." +
                    "C_JBR AS [T_SP.C_JBR], \r\n            T.C_TM AS [T_SP.C_TM], \r\n            T.C_BZ" +
                    " AS [T_SP.C_BZ], \r\n            True AS _from0\r\n        FROM WXDataDataModelStore" +
                    "Container.T_SP AS T\r\n    ) AS T1");
        }
        
        /// <Summary>
        /// return view for SBIIMS_JXC_TJBB_CGYCGEntities.T_SPDW
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView21()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("SBIIMS_JXC_TJBB_CGYCGEntities.T_SPDW", @"
    SELECT VALUE -- Constructing T_SPDW
        [WX.Data.DataModel.T_SPDW](T1.[T_SPDW.C_DM], T1.[T_SPDW.C_DW], T1.[T_SPDW.C_JYBZ], T1.[T_SPDW.C_XTCSBZ], T1.[T_SPDW.C_BZ])
    FROM (
        SELECT 
            T.C_DM AS [T_SPDW.C_DM], 
            T.C_DW AS [T_SPDW.C_DW], 
            T.C_JYBZ AS [T_SPDW.C_JYBZ], 
            T.C_XTCSBZ AS [T_SPDW.C_XTCSBZ], 
            T.C_BZ AS [T_SPDW.C_BZ], 
            True AS _from0
        FROM WXDataDataModelStoreContainer.T_SPDW AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for SBIIMS_JXC_TJBB_CGYCGEntities.T_SPYS
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView22()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("SBIIMS_JXC_TJBB_CGYCGEntities.T_SPYS", @"
    SELECT VALUE -- Constructing T_SPYS
        [WX.Data.DataModel.T_SPYS](T1.[T_SPYS.C_ID], T1.[T_SPYS.C_XH], T1.[T_SPYS.C_YS], T1.[T_SPYS.C_JYBZ], T1.[T_SPYS.C_XTCSBZ], T1.[T_SPYS.C_BZ])
    FROM (
        SELECT 
            T.C_ID AS [T_SPYS.C_ID], 
            T.C_XH AS [T_SPYS.C_XH], 
            T.C_YS AS [T_SPYS.C_YS], 
            T.C_JYBZ AS [T_SPYS.C_JYBZ], 
            T.C_XTCSBZ AS [T_SPYS.C_XTCSBZ], 
            T.C_BZ AS [T_SPYS.C_BZ], 
            True AS _from0
        FROM WXDataDataModelStoreContainer.T_SPYS AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for SBIIMS_JXC_TJBB_CGYCGEntities.T_YG
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView23()
        {
            System.Text.StringBuilder viewString = new System.Text.StringBuilder(2438);
            viewString.Append("\r\n    SELECT VALUE -- Constructing T_YG\r\n        [WX.Data.DataModel.T_YG](T1.[T_");
            viewString.Append("YG.C_FBID], T1.[T_YG.C_GXRQ], T1.[T_YG.C_CJRQ], T1.[T_YG.C_ID], T1.[T_YG.C_XM], ");
            viewString.Append("T1.[T_YG.C_XMJM], T1.[T_YG.C_XBH], T1.[T_YG.C_XB], T1.[T_YG.C_NL], T1.[T_YG.C_XX");
            viewString.Append("], T1.[T_YG.C_XL], T1.[T_YG.C_HF], T1.[T_YG.C_ZN], T1.[T_YG.C_DWBM], T1.[T_YG.C_");
            viewString.Append("LXDH], T1.[T_YG.C_LXDZ], T1.[T_YG.C_JYBZ], T1.[T_YG.C_XTCSBZ], T1.[T_YG.C_XNBZ],");
            viewString.Append(" T1.[T_YG.C_JBR], T1.[T_YG.C_CZY], T1.[T_YG.C_ZW], T1.[T_YG.C_GZJS], T1.[T_YG.C_");
            viewString.Append("TCBL], T1.[T_YG.C_GF], T1.[T_YG.C_RZRQ], T1.[T_YG.C_HTNX], T1.[T_YG.C_YLZBZ], T1");
            viewString.Append(".[T_YG.C_GZNX], T1.[T_YG.C_CZYBZ], T1.[T_YG.C_SHYBZ], T1.[T_YG.C_YWYBZ], T1.[T_Y");
            viewString.Append("G.C_FZYW], T1.[T_YG.C_DWBMLJ], T1.[T_YG.C_BTFYX], T1.[T_YG.C_LZRQ], T1.[T_YG.C_Z");
            viewString.Append("P], T1.[T_YG.C_DY], T1.[T_YG.C_BZ])\r\n    FROM (\r\n        SELECT \r\n            T.");
            viewString.Append("C_FBID AS [T_YG.C_FBID], \r\n            T.C_GXRQ AS [T_YG.C_GXRQ], \r\n            ");
            viewString.Append("T.C_CJRQ AS [T_YG.C_CJRQ], \r\n            T.C_ID AS [T_YG.C_ID], \r\n            T.");
            viewString.Append("C_XM AS [T_YG.C_XM], \r\n            T.C_XMJM AS [T_YG.C_XMJM], \r\n            T.C_");
            viewString.Append("XBH AS [T_YG.C_XBH], \r\n            T.C_XB AS [T_YG.C_XB], \r\n            T.C_NL A");
            viewString.Append("S [T_YG.C_NL], \r\n            T.C_XX AS [T_YG.C_XX], \r\n            T.C_XL AS [T_Y");
            viewString.Append("G.C_XL], \r\n            T.C_HF AS [T_YG.C_HF], \r\n            T.C_ZN AS [T_YG.C_ZN");
            viewString.Append("], \r\n            T.C_DWBM AS [T_YG.C_DWBM], \r\n            T.C_LXDH AS [T_YG.C_LX");
            viewString.Append("DH], \r\n            T.C_LXDZ AS [T_YG.C_LXDZ], \r\n            T.C_JYBZ AS [T_YG.C_");
            viewString.Append("JYBZ], \r\n            T.C_XTCSBZ AS [T_YG.C_XTCSBZ], \r\n            T.C_XNBZ AS [T");
            viewString.Append("_YG.C_XNBZ], \r\n            T.C_JBR AS [T_YG.C_JBR], \r\n            T.C_CZY AS [T_");
            viewString.Append("YG.C_CZY], \r\n            T.C_ZW AS [T_YG.C_ZW], \r\n            T.C_GZJS AS [T_YG.");
            viewString.Append("C_GZJS], \r\n            T.C_TCBL AS [T_YG.C_TCBL], \r\n            T.C_GF AS [T_YG.");
            viewString.Append("C_GF], \r\n            T.C_RZRQ AS [T_YG.C_RZRQ], \r\n            T.C_HTNX AS [T_YG.");
            viewString.Append("C_HTNX], \r\n            T.C_YLZBZ AS [T_YG.C_YLZBZ], \r\n            T.C_GZNX AS [T");
            viewString.Append("_YG.C_GZNX], \r\n            T.C_CZYBZ AS [T_YG.C_CZYBZ], \r\n            T.C_SHYBZ ");
            viewString.Append("AS [T_YG.C_SHYBZ], \r\n            T.C_YWYBZ AS [T_YG.C_YWYBZ], \r\n            T.C_");
            viewString.Append("FZYW AS [T_YG.C_FZYW], \r\n            T.C_DWBMLJ AS [T_YG.C_DWBMLJ], \r\n          ");
            viewString.Append("  T.C_BTFYX AS [T_YG.C_BTFYX], \r\n            T.C_LZRQ AS [T_YG.C_LZRQ], \r\n      ");
            viewString.Append("      T.C_ZP AS [T_YG.C_ZP], \r\n            T.C_DY AS [T_YG.C_DY], \r\n            ");
            viewString.Append("T.C_BZ AS [T_YG.C_BZ], \r\n            True AS _from0\r\n        FROM WXDataDataMode");
            viewString.Append("lStoreContainer.T_YG AS T\r\n    ) AS T1");
            return new System.Collections.Generic.KeyValuePair<string, string>("SBIIMS_JXC_TJBB_CGYCGEntities.T_YG", viewString.ToString());
        }
    }
}
